// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VNPT.Models.Data;

#nullable disable

namespace VNPT.Migrations
{
    [DbContext(typeof(TestDBContext))]
    [Migration("20260618031841_AddRoleToUserTable")]
    partial class AddRoleToUserTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("VNPT.Models.MENU", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ACTION_NAME")
                        .HasColumnType("TEXT");

                    b.Property<string>("CONTROLLER_NAME")
                        .HasColumnType("TEXT");

                    b.Property<string>("ICON_CLASS")
                        .HasColumnType("TEXT");

                    b.Property<string>("MENU_NAME")
                        .HasColumnType("TEXT");

                    b.Property<string>("MENU_TITLE")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PARENT_ID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ROUTE_URL")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("MENU");
                });

            modelBuilder.Entity("VNPT.Models.USER", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FULLNAME")
                        .HasColumnType("TEXT");

                    b.Property<int>("ISDELETED")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PASSWORD")
                        .HasColumnType("TEXT");

                    b.Property<string>("ROLE")
                        .HasColumnType("TEXT");

                    b.Property<string>("USERNAME")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("USERS");
                });
#pragma warning restore 612, 618
        }
    }
}
