// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VNPT.Models.Data;

#nullable disable

namespace VNPT.Migrations
{
    [DbContext(typeof(TestDBContext))]
    [Migration("20260617091555_InitDatabase")]
    partial class InitDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.28");

            modelBuilder.Entity("VNPT.Models.USER", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("FULLNAME")
                        .HasColumnType("TEXT");

                    b.Property<int>("ISDELETED")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PASSWORD")
                        .HasColumnType("TEXT");

                    b.Property<string>("USERNAME")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("USERS");
                });
#pragma warning restore 612, 618
        }
    }
}
